# hotel.yaml — 我们项目的配置（路径已适配 AutoDL）
use_wandb: False
use_sky: False
use_dynamic: False
use_loop: True
use_pose_refine: False
use_metric: True

mode: 'vo'

device:
  tracker: 'cuda:0'
  mapper: 'cuda:0'

dataset:
  root: /root/autodl-tmp/data/hotel/
  module: datasets.rtgslam
  rgb_strip: 1

middleware:
  cov_times: 100
  max_cov: 1e4
  max_depth: 6

output:
  save_dir: /root/autodl-tmp/VINGS-Mono-SLAM-Course/results/hotel/

intrinsic:
  H: 720
  W: 1280
  fu: 605.371
  fv: 605.371
  cu: 366.510
  cv: 635.3085
  resolution_scale: 1.0
  bg: 0

frontend:
  weight: /root/autodl-tmp/VINGS-Mono-SLAM-Course/ckpts/droid.pth
  image_size: [344, 616]
  buffer: 80
  filter_thresh: 2.4
  c2i: None
  warm_up: 8
  beta: 0.3
  frontend_nms: 1
  keyframe_thresh: 4.0
  frontend_window: 5
  frontend_thresh: 4.0
  frontend_radius: 2
  active_window: 12
  max_factors: 48
  far_threshold: 0.02
  inac_range: 3
  mask_threshold: -1.0
  skip_edge: [-4,-5,-6]
  translation_threshold: 0.3
  show_plot: False

adc_args:
  accum_thresh: 0.98
training_args:
  num_keyframe: 8
  iters: 50
  lr:
    _xyz_lr: 0.00002
    _rgb_lr: 0.0001
    _opacity_lr: 0.02
    _scaling_lr: 0.001
    _rotation_lr: 0.001
  loss_weights:
    rgb_loss: 1.0
    depth_loss: 1.0
    alpha_loss: 0.5
    normal_loss: 0.05
    dist_loss: 0.0
    smooth_loss: 0.0

use_vis: False

use_storage_manager: False

looper:
  lightglue_weight_dir: /root/autodl-tmp/VINGS-Mono-SLAM-Course/ckpts/lightglue/
  onnx_w: 512
  H: 344
  W: 616
  loop_radius: 15
  is_loop_min_match_num: 45
  search_num: 30
  is_loop_mse_threshold: 0.15
  is_loop_med_times: 100.0
