frontend_only: True
use_wandb: False
use_sky: False
use_dynamic: False
use_pose_refine: False
use_metric: False
use_refine: False
debug_mode: False

mode: 'vo' # 'vo' or 'vio'


device:
  tracker: 'cuda:0'
  mapper: 'cuda:0'

dataset:
  root: /root/autodl-tmp/data/waymo/Scene01/
  module: datasets.waymo
  rgb_strip: 1

middleware:
  cov_times: 70000
  max_cov: 1e5
  max_depth: 80

output:
  save_dir: /root/autodl-tmp/VINGS-Mono-SLAM-Course/results/frontend/waymo01/

# 707.0912 707.0912 601.8873 183.1104
intrinsic: 
  fu: 2044.508
  fv: 2044.508
  cu: 633.2422 # cy
  cv: 979.5746 # cx
  H: 1280
  W: 1920

frontend:
  weight: /root/autodl-tmp/VINGS-Mono-SLAM-Course/ckpts/droid.pth
  image_size: [344, 616]
  buffer: 80
  filter_thresh: 2.4 # 2.4
  c2i: None
  # visual_only: 0 # 0 means VIO and 1 means VO.
  warm_up: 8
  beta: 0.3
  frontend_nms: 1
  keyframe_thresh: 1.0 # 4.0
  frontend_window: 5
  frontend_thresh: 16.0 
  frontend_radius: 2
  active_window: 12
  # CovisibleGraph
  max_factors: 48
  far_threshold: 0.02
  inac_range: 3
  mask_threshold: -1.0
  skip_edge: [-4,-5,-6]
  translation_threshold: 0.5
  # Vis.
  show_plot: False

adc_args:
  accum_thresh: 0.98
training_args:
  num_keyframe: 8
  iters: 50
  lr: # Copy form 2DGS.
    _xyz_lr: 0.0001
    _rgb_lr: 0.0003
    _opacity_lr: 0.07
    _scaling_lr: 0.00001
    _rotation_lr: 0.001
  loss_weights:
    rgb_loss: 1.0
    depth_loss: 1.0
    alpha_loss: 1.0  # 10.0
    normal_loss: 2.0 # 0.05
    dist_loss: 0.0


use_vis: False
vis:
  bev_w2c: [[ 8.82613957e-01, -2.60401923e-02,  4.69376726e-01, -8.61934866e+00],
       [ 1.66225480e-01,  9.51249234e-01, -2.59796043e-01, 2.12136420e+01],
       [-4.39729112e-01,  3.07321985e-01,  8.43914395e-01, 3.38775142e+01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, 1.00000000e+00]]
  bev_intrinsic_dict:
    H: 758
    W: 1372
    fu: 656.44725606860459
    fv: 656.44725606860459
    cu: 378.5 # cy
    cv: 685.5 # cx
  pose_scale: 1.0



# 2024/10/01
use_storage_manager: True
storage_manager:
  distance_threshold: 30.0